### ISSUE TITLE
extra_params is currently ignored in head version

### ISSUE THREAD

**Issue by drevicko** [gsi-upm/senpy#13]
extra_params that aren't in nif_params are currently ignored.

**Comment by balkian** [comment]
@drevicko check the latest version. There are a couple of tests for that scenario:

https://github.com/gsi-upm/senpy/blob/master/tests/test_api.py#L33

https://github.com/gsi-upm/senpy/blob/master/tests/test_blueprints.py#L77

Feel free to re-open if it keeps happening :)

**Comment by drevicko** [comment]
no, looks fixed, will reopen if it pops up again. 

ps: the current head build doesn't pip install, as there is no file called VERSION (it's been added to .gitignore - perhaps it shouldn't be ignored?). I made a comment on the commit, perhaps you got an email about it?
