### ISSUE TITLE
to-VAD conversion as an average or sum?

### ISSUE THREAD

**Issue by drevicko** [gsi-upm/senpy#16]
I think it makes more sense to convert to VAD as a (weighted) average.

(https://github.com/gsi-upm/senpy/blob/master/senpy/plugins/conversion/centroids.py#L11)

When weights aren't present, we can use 0 (emotions not present) and 1 (emotion present).

Should we include Hesam in the discussion?

**Comment by drevicko** [comment]
Oh, another thing, when we're using centroids, we need to have a centroid for Neutral, or at least have a principled way to deal with it.

Ideally this would be (0,0,0); in which case we could probably get by without it. 

BUT, the current centroids from the ANEW plugin appear to sit in a VAD space with each dimension between 0 and 10. IN this case, the Neutral point ought to be (5,5,5) - this is NOT what the current conversion does, nor what the ANEW plugin does!

With these centroids, it makes more sense to me to first subtract (5,5,5) from each centroid, then calculate the average over detected emotion categories, then add (5,5,5) again to get back to the same representation as the original centroids.

**Comment by balkian** [comment]
> I think it makes more sense to convert to VAD as a (weighted) average.

Makes sense, and it's easy to add.

> Oh, another thing, when we're using centroids, we need to have a centroid for Neutral, or at least have a principled way to deal with it.

Agreed.

> With these centroids, it makes more sense to me to first subtract (5,5,5) from each centroid, then calculate the average over detected emotion categories, then add (5,5,5) again to get back to the same representation as the original centroids.

AFAIK, this is the same as not substracting it in the first place. `E<x-C> + C = E<x> - C + C = E<x>`.

Or, for a weighted average: 

<img src="https://latex.codecogs.com/gif.latex?sum_{0}^{N}&space;(w_i*(v_i-C))&space;&plus;&space;C&space;=&space;sum_{0}^{N}&space;(w_i*v_i)&space;-&space;C*sum_0^N(w_i)&space;&plus;&space;C&space;=&space;sum_{0}^{N}&space;(w_i*v_i))" title="sum_{0}^{N} (w_i*(v_i-C)) + C = sum_{0}^{N} (w_i*v_i) - C*sum_0^N(w_i) + C = sum_{0}^{N} (w_i*v_i))" />

> BUT, the current centroids from the ANEW plugin appear to sit in a VAD space with each dimension between 0 and 10. IN this case, the Neutral point ought to be (5,5,5) - this is NOT what the current conversion does, nor what the ANEW plugin does!

*appear to sit*. Isn't that only based on the average of all the values in the dataset?

**Comment by drevicko** [comment]
Yes, of course, adding/subtracting (5,5,5) makes no sense (:

> Isn't that only based on the average of all the values in the dataset?

so, the centroids are based on a particular data set? I always wondered where they came from (:

It should be the average of the Neutral texts in the data set though, not of all texts. 

In an ideal world, we would have a centroid for Neutral and the detection algorithms would provide a probability/intensity for Neutral (perhaps binary) to be included in the average calculation. I guess for binary detection, Neutral could be taken as the absence of any other emotion. 

For analyses with intensities/probabilities, it could be more complex (ie: in our case, the emotion detectors for each class are independant, so you can't do $1-\sum other emotion probabilities$). I'll have to think on that a bit...

**Comment by drevicko** [comment]
The centroid conversions code is currently returning just a sum. I believe this is quite wrong if there are more than one emotion present.

Also, there is no treatment of neutral content (ie: no emotion categories present). There should be a way to deal with this (eg: have a neutral centroid, and if no emotions are present, use it and issue a warning and use (0,0,0) if no neutral centroids is found)
