### ISSUE TITLE
Failure rendering web interface when only one analysis plugin

### ISSUE THREAD

**Issue by drevicko** [gsi-upm/senpy#21]
The result of the 'http://localhost:5000/api/plugins/' call returns a single Object when there is only one plugin. When there are more than one, it's an Array of Objects.

The loop in the $(document).ready function assumes it's an Array, so instead of looping through plugin Objects, it loops through plugin Object attributes when there is only one Object, and all the html rendering code falls down.

**Comment by balkian** [comment]
Hey Ian, thanks a lot for spotting this!

It should be fixed in 0.8.5.
