### ISSUE TITLE
pip screws with logging config

### ISSUE THREAD

**Issue by drevicko** [gsi-upm/senpy#23]
pip [screws up the logging configuration](https://github.com/pypa/pip/issues/3043).

This is annoying when debugging. One easy ugly hack to deal with this is to simply [comment out the call to pip](https://github.com/gsi-upm/senpy/blob/master/senpy/extensions.py#L304) (since when debugging we probably already have dependencies installed, no need to check).

It might be nice to have an option to not check pip? Or implement some sort of workaround to get logging back into the previous state after calling pip, but that sounds tedious!

**Comment by Lucas-C** [comment]
I submitted a PR in #3043

**Comment by drevicko** [comment]
Closed by 7e5b55ff9cab00d8d3f4421465fdc40ac5edded1
