### ISSUE TITLE
Bug in Ekman2VAD  backwards conversion method 

### ISSUE THREAD

**Issue by ddwell** [gsi-upm/senpy#31]
> https://github.com/gsi-upm/senpy/blob/master/senpy/plugins/conversion/centroids.py

`def _backwards_conversion(self, original):`

This method does not work appropriately. 
I believe, `abs(min(d))` should be used instead of `min(d)`

**Comment by ddwell** [comment]
@balkian @ianwoo

**Comment by ddwell** [comment]
I propose the following code:

```
def _backwards_conversion(original):    
        """Find the closest category"""
        
        dimensions = list(centroids.values())[0]
        
        def distance(e1, e2):
            return sum((e1[k] - e2.get(k, 0)) for k in dimensions)

        distances = { state:abs(distance(centroids[state], original)) for state in centroids }
        mindistance = max(distances.values())
        
        for state in distances:
            if distances[state] < mindistance:
                mindistance = distances[state]
                emotion = state
                
        result = Emotion(onyx__hasEmotionCategory=emotion)
        return result
```
for testing it in Ipython notebook:
```
feature_text = {
    "A": 5.0, 
    "D": 5.0, 
    "V": 5.0
}

from senpy.models import Emotion

emotion = Emotion() 
for dimension in ["V","A","D"]:
    emotion[dimension] = float((feature_text[dimension])) 
    
_backwards_conversion(emotion)

```

 for the implementation do not forget to put `self`

**Comment by balkian** [comment]
You're right. Since we're gonna improve it, I'd suggest sth like:

```
NEUTRAL = 0
def _backwards_conversion(original):    
        """Find the closest category"""
        
        dimensions = set(k.keys() for i in centroids.values()))
        
        def distance(centroid):
            return sum((centroid.get(k, NEUTRAL) - original.get(k, NEUTRAL))**2 for k in dimensions)

        emotion = min(centroids, key=lambda x: distance(centroids[x])
                
        result = Emotion(onyx__hasEmotionCategory=emotion)
        return result
```

**Comment by drevicko** [comment]
In the current code, the distance is something like a taxicab metric, though there's a missing `abs` (ie: `sum(abs(e1-e2))`). Fernando, you're suggested code is using the usual Euclidean metric `sum((e1-e2)**2)`. Was there a motivation behind the choice of metric?

I'd suggest having neutral as a centroid. We could have a default if it's not defined in the converter's senpy file. For the current centroids, it's `(5,5,5)j`, so using `NEUTRAL=0` will cause strange results.

ps: I like using a `set` and `min(...,key=...)`, compact and computationally efficient (:
