### ISSUE TITLE
Extra_params is duplicated in some plugins

### ISSUE THREAD

**Issue by balkian** [gsi-upm/senpy#4]

**Comment by drevicko** [comment]
not sure if it's the same thing you're referring to here, but our hashtag plugin, based on the WNA plugin, was storing the info parameter of the constructor as a (non-private) instance variable. Easy fixed by appending an underscore to the instance variable name (thus making it private).

**Comment by balkian** [comment]
@drevicko please, don't assign the info or id attributes manually. The main class already does it for you:

https://github.com/gsi-upm/senpy/blob/master/senpy/plugins.py#L21
