### ISSUE TITLE
Only sentiment-140 is avaliable

### ISSUE THREAD

**Issue by wiedersehne** [gsi-upm/senpy#40]
I use senpy like this:
from senpy.client import Client

c = Client('http://latest.senpy.cluster.gsi.dit.upm.es/api')
#c = Client('http://127.0.0.1:5000/api')
r = c.analyse('I am sad', algorithm='sentiText')
print(r)

The an ERROR: senpy.models.Error: The algorithm 'sentitext' is not valid
Valid algorithms: dict_keys(['split', 'ekman2fsre', 'sentiment140', 'rand', 'emorand', 'ekman2pad'])

But in the test page, the algorithms like sentiText, EmoTextANEW are available. How should I use them in my own program.
Thank you!

**Comment by balkian** [comment]
You're trying to use an algorithm that is not available in the **latest** endpoint. 

You can get a list of available plugins using the client:

```
>>> from senpy.client import Client
>>> c = client.Client('http://latest.senpy.cluster.gsi.dit.upm.es/api')
>>> print(c.plugins().keys()) # Get a list of available plugins
dict_keys(['sentiment140', 'EmoRand', 'split', 'Rand'])
```

You probably meant to use this endpoint instead: http://senpy.cluster.gsi.dit.upm.es

**Comment by wiedersehne** [comment]
Yes!
Thank you very much!
